#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

feh --bg-fill /home/megame/BSPWM/BSPWM/blue.png

#Autostart applications
sxhkd &
picom --config ~/.config/picom/picom.conf &
dunst &
polybar &

